//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: fsapi-v1.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Api_V1_InboxClient`, then call methods of this protocol to make API calls.
internal protocol Api_V1_InboxClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? { get }

  func quickInbox(
    _ request: Api_V1_QuickInboxRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_QuickInboxRequest, Api_V1_QuickInboxResponse>
}

extension Api_V1_InboxClientProtocol {
  internal var serviceName: String {
    return "api.v1.Inbox"
  }

  /// Unary call to QuickInbox
  ///
  /// - Parameters:
  ///   - request: Request to send to QuickInbox.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func quickInbox(
    _ request: Api_V1_QuickInboxRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_QuickInboxRequest, Api_V1_QuickInboxResponse> {
    return self.makeUnaryCall(
      path: Api_V1_InboxClientMetadata.Methods.quickInbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuickInboxInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Api_V1_InboxClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Api_V1_InboxNIOClient")
internal final class Api_V1_InboxClient: Api_V1_InboxClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Api_V1_InboxClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.v1.Inbox service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Api_V1_InboxNIOClient: Api_V1_InboxClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_InboxClientInterceptorFactoryProtocol?

  /// Creates a client for the api.v1.Inbox service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_V1_InboxAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? { get }

  func makeQuickInboxCall(
    _ request: Api_V1_QuickInboxRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_QuickInboxRequest, Api_V1_QuickInboxResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_InboxAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_V1_InboxClientMetadata.serviceDescriptor
  }

  internal var interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeQuickInboxCall(
    _ request: Api_V1_QuickInboxRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_QuickInboxRequest, Api_V1_QuickInboxResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_InboxClientMetadata.Methods.quickInbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuickInboxInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_InboxAsyncClientProtocol {
  internal func quickInbox(
    _ request: Api_V1_QuickInboxRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_QuickInboxResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_InboxClientMetadata.Methods.quickInbox.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQuickInboxInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Api_V1_InboxAsyncClient: Api_V1_InboxAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_InboxClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_InboxClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Api_V1_InboxClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'quickInbox'.
  func makeQuickInboxInterceptors() -> [ClientInterceptor<Api_V1_QuickInboxRequest, Api_V1_QuickInboxResponse>]
}

internal enum Api_V1_InboxClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Inbox",
    fullName: "api.v1.Inbox",
    methods: [
      Api_V1_InboxClientMetadata.Methods.quickInbox,
    ]
  )

  internal enum Methods {
    internal static let quickInbox = GRPCMethodDescriptor(
      name: "QuickInbox",
      path: "/api.v1.Inbox/QuickInbox",
      type: GRPCCallType.unary
    )
  }
}

/// Usage: instantiate `Api_V1_EntriesClient`, then call methods of this protocol to make API calls.
internal protocol Api_V1_EntriesClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? { get }

  func getEntryDetail(
    _ request: Api_V1_GetEntryDetailRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_GetEntryDetailRequest, Api_V1_GetEntryDetailResponse>

  func createEntry(
    _ request: Api_V1_CreateEntryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_CreateEntryRequest, Api_V1_CreateEntryResponse>

  func updateEntry(
    _ request: Api_V1_UpdateEntryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_UpdateEntryRequest, Api_V1_UpdateEntryResponse>

  func deleteEntry(
    _ request: Api_V1_DeleteEntryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_DeleteEntryRequest, Api_V1_DeleteEntryResponse>

  func listGroupChildren(
    _ request: Api_V1_ListGroupChildrenRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_ListGroupChildrenRequest, Api_V1_ListGroupChildrenResponse>

  func changeParent(
    _ request: Api_V1_ChangeParentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_ChangeParentRequest, Api_V1_ChangeParentResponse>

  func writeFile(
    callOptions: CallOptions?
  ) -> ClientStreamingCall<Api_V1_WriteFileRequest, Api_V1_WriteFileResponse>

  func readFile(
    _ request: Api_V1_ReadFileRequest,
    callOptions: CallOptions?,
    handler: @escaping (Api_V1_ReadFileResponse) -> Void
  ) -> ServerStreamingCall<Api_V1_ReadFileRequest, Api_V1_ReadFileResponse>
}

extension Api_V1_EntriesClientProtocol {
  internal var serviceName: String {
    return "api.v1.Entries"
  }

  /// Unary call to GetEntryDetail
  ///
  /// - Parameters:
  ///   - request: Request to send to GetEntryDetail.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getEntryDetail(
    _ request: Api_V1_GetEntryDetailRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_GetEntryDetailRequest, Api_V1_GetEntryDetailResponse> {
    return self.makeUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.getEntryDetail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetEntryDetailInterceptors() ?? []
    )
  }

  /// Unary call to CreateEntry
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateEntry.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createEntry(
    _ request: Api_V1_CreateEntryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_CreateEntryRequest, Api_V1_CreateEntryResponse> {
    return self.makeUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.createEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateEntryInterceptors() ?? []
    )
  }

  /// Unary call to UpdateEntry
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateEntry.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateEntry(
    _ request: Api_V1_UpdateEntryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_UpdateEntryRequest, Api_V1_UpdateEntryResponse> {
    return self.makeUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.updateEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateEntryInterceptors() ?? []
    )
  }

  /// Unary call to DeleteEntry
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteEntry.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteEntry(
    _ request: Api_V1_DeleteEntryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_DeleteEntryRequest, Api_V1_DeleteEntryResponse> {
    return self.makeUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.deleteEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteEntryInterceptors() ?? []
    )
  }

  /// Unary call to ListGroupChildren
  ///
  /// - Parameters:
  ///   - request: Request to send to ListGroupChildren.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listGroupChildren(
    _ request: Api_V1_ListGroupChildrenRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_ListGroupChildrenRequest, Api_V1_ListGroupChildrenResponse> {
    return self.makeUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.listGroupChildren.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListGroupChildrenInterceptors() ?? []
    )
  }

  /// Unary call to ChangeParent
  ///
  /// - Parameters:
  ///   - request: Request to send to ChangeParent.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func changeParent(
    _ request: Api_V1_ChangeParentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_ChangeParentRequest, Api_V1_ChangeParentResponse> {
    return self.makeUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.changeParent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChangeParentInterceptors() ?? []
    )
  }

  /// Client streaming call to WriteFile
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata, status and response.
  internal func writeFile(
    callOptions: CallOptions? = nil
  ) -> ClientStreamingCall<Api_V1_WriteFileRequest, Api_V1_WriteFileResponse> {
    return self.makeClientStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.writeFile.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWriteFileInterceptors() ?? []
    )
  }

  /// Server streaming call to ReadFile
  ///
  /// - Parameters:
  ///   - request: Request to send to ReadFile.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func readFile(
    _ request: Api_V1_ReadFileRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Api_V1_ReadFileResponse) -> Void
  ) -> ServerStreamingCall<Api_V1_ReadFileRequest, Api_V1_ReadFileResponse> {
    return self.makeServerStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.readFile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReadFileInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Api_V1_EntriesClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Api_V1_EntriesNIOClient")
internal final class Api_V1_EntriesClient: Api_V1_EntriesClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.v1.Entries service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Api_V1_EntriesNIOClient: Api_V1_EntriesClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol?

  /// Creates a client for the api.v1.Entries service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_V1_EntriesAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? { get }

  func makeGetEntryDetailCall(
    _ request: Api_V1_GetEntryDetailRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_GetEntryDetailRequest, Api_V1_GetEntryDetailResponse>

  func makeCreateEntryCall(
    _ request: Api_V1_CreateEntryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_CreateEntryRequest, Api_V1_CreateEntryResponse>

  func makeUpdateEntryCall(
    _ request: Api_V1_UpdateEntryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_UpdateEntryRequest, Api_V1_UpdateEntryResponse>

  func makeDeleteEntryCall(
    _ request: Api_V1_DeleteEntryRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_DeleteEntryRequest, Api_V1_DeleteEntryResponse>

  func makeListGroupChildrenCall(
    _ request: Api_V1_ListGroupChildrenRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_ListGroupChildrenRequest, Api_V1_ListGroupChildrenResponse>

  func makeChangeParentCall(
    _ request: Api_V1_ChangeParentRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_ChangeParentRequest, Api_V1_ChangeParentResponse>

  func makeWriteFileCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncClientStreamingCall<Api_V1_WriteFileRequest, Api_V1_WriteFileResponse>

  func makeReadFileCall(
    _ request: Api_V1_ReadFileRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Api_V1_ReadFileRequest, Api_V1_ReadFileResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_EntriesAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_V1_EntriesClientMetadata.serviceDescriptor
  }

  internal var interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetEntryDetailCall(
    _ request: Api_V1_GetEntryDetailRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_GetEntryDetailRequest, Api_V1_GetEntryDetailResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.getEntryDetail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetEntryDetailInterceptors() ?? []
    )
  }

  internal func makeCreateEntryCall(
    _ request: Api_V1_CreateEntryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_CreateEntryRequest, Api_V1_CreateEntryResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.createEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateEntryInterceptors() ?? []
    )
  }

  internal func makeUpdateEntryCall(
    _ request: Api_V1_UpdateEntryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_UpdateEntryRequest, Api_V1_UpdateEntryResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.updateEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateEntryInterceptors() ?? []
    )
  }

  internal func makeDeleteEntryCall(
    _ request: Api_V1_DeleteEntryRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_DeleteEntryRequest, Api_V1_DeleteEntryResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.deleteEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteEntryInterceptors() ?? []
    )
  }

  internal func makeListGroupChildrenCall(
    _ request: Api_V1_ListGroupChildrenRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_ListGroupChildrenRequest, Api_V1_ListGroupChildrenResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.listGroupChildren.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListGroupChildrenInterceptors() ?? []
    )
  }

  internal func makeChangeParentCall(
    _ request: Api_V1_ChangeParentRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_ChangeParentRequest, Api_V1_ChangeParentResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.changeParent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChangeParentInterceptors() ?? []
    )
  }

  internal func makeWriteFileCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncClientStreamingCall<Api_V1_WriteFileRequest, Api_V1_WriteFileResponse> {
    return self.makeAsyncClientStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.writeFile.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWriteFileInterceptors() ?? []
    )
  }

  internal func makeReadFileCall(
    _ request: Api_V1_ReadFileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Api_V1_ReadFileRequest, Api_V1_ReadFileResponse> {
    return self.makeAsyncServerStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.readFile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReadFileInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_EntriesAsyncClientProtocol {
  internal func getEntryDetail(
    _ request: Api_V1_GetEntryDetailRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_GetEntryDetailResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.getEntryDetail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetEntryDetailInterceptors() ?? []
    )
  }

  internal func createEntry(
    _ request: Api_V1_CreateEntryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_CreateEntryResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.createEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateEntryInterceptors() ?? []
    )
  }

  internal func updateEntry(
    _ request: Api_V1_UpdateEntryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_UpdateEntryResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.updateEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateEntryInterceptors() ?? []
    )
  }

  internal func deleteEntry(
    _ request: Api_V1_DeleteEntryRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_DeleteEntryResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.deleteEntry.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteEntryInterceptors() ?? []
    )
  }

  internal func listGroupChildren(
    _ request: Api_V1_ListGroupChildrenRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_ListGroupChildrenResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.listGroupChildren.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListGroupChildrenInterceptors() ?? []
    )
  }

  internal func changeParent(
    _ request: Api_V1_ChangeParentRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_ChangeParentResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_EntriesClientMetadata.Methods.changeParent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChangeParentInterceptors() ?? []
    )
  }

  internal func writeFile<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_WriteFileResponse where RequestStream: Sequence, RequestStream.Element == Api_V1_WriteFileRequest {
    return try await self.performAsyncClientStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.writeFile.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWriteFileInterceptors() ?? []
    )
  }

  internal func writeFile<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_WriteFileResponse where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Api_V1_WriteFileRequest {
    return try await self.performAsyncClientStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.writeFile.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWriteFileInterceptors() ?? []
    )
  }

  internal func readFile(
    _ request: Api_V1_ReadFileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Api_V1_ReadFileResponse> {
    return self.performAsyncServerStreamingCall(
      path: Api_V1_EntriesClientMetadata.Methods.readFile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeReadFileInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Api_V1_EntriesAsyncClient: Api_V1_EntriesAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_EntriesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Api_V1_EntriesClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getEntryDetail'.
  func makeGetEntryDetailInterceptors() -> [ClientInterceptor<Api_V1_GetEntryDetailRequest, Api_V1_GetEntryDetailResponse>]

  /// - Returns: Interceptors to use when invoking 'createEntry'.
  func makeCreateEntryInterceptors() -> [ClientInterceptor<Api_V1_CreateEntryRequest, Api_V1_CreateEntryResponse>]

  /// - Returns: Interceptors to use when invoking 'updateEntry'.
  func makeUpdateEntryInterceptors() -> [ClientInterceptor<Api_V1_UpdateEntryRequest, Api_V1_UpdateEntryResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteEntry'.
  func makeDeleteEntryInterceptors() -> [ClientInterceptor<Api_V1_DeleteEntryRequest, Api_V1_DeleteEntryResponse>]

  /// - Returns: Interceptors to use when invoking 'listGroupChildren'.
  func makeListGroupChildrenInterceptors() -> [ClientInterceptor<Api_V1_ListGroupChildrenRequest, Api_V1_ListGroupChildrenResponse>]

  /// - Returns: Interceptors to use when invoking 'changeParent'.
  func makeChangeParentInterceptors() -> [ClientInterceptor<Api_V1_ChangeParentRequest, Api_V1_ChangeParentResponse>]

  /// - Returns: Interceptors to use when invoking 'writeFile'.
  func makeWriteFileInterceptors() -> [ClientInterceptor<Api_V1_WriteFileRequest, Api_V1_WriteFileResponse>]

  /// - Returns: Interceptors to use when invoking 'readFile'.
  func makeReadFileInterceptors() -> [ClientInterceptor<Api_V1_ReadFileRequest, Api_V1_ReadFileResponse>]
}

internal enum Api_V1_EntriesClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Entries",
    fullName: "api.v1.Entries",
    methods: [
      Api_V1_EntriesClientMetadata.Methods.getEntryDetail,
      Api_V1_EntriesClientMetadata.Methods.createEntry,
      Api_V1_EntriesClientMetadata.Methods.updateEntry,
      Api_V1_EntriesClientMetadata.Methods.deleteEntry,
      Api_V1_EntriesClientMetadata.Methods.listGroupChildren,
      Api_V1_EntriesClientMetadata.Methods.changeParent,
      Api_V1_EntriesClientMetadata.Methods.writeFile,
      Api_V1_EntriesClientMetadata.Methods.readFile,
    ]
  )

  internal enum Methods {
    internal static let getEntryDetail = GRPCMethodDescriptor(
      name: "GetEntryDetail",
      path: "/api.v1.Entries/GetEntryDetail",
      type: GRPCCallType.unary
    )

    internal static let createEntry = GRPCMethodDescriptor(
      name: "CreateEntry",
      path: "/api.v1.Entries/CreateEntry",
      type: GRPCCallType.unary
    )

    internal static let updateEntry = GRPCMethodDescriptor(
      name: "UpdateEntry",
      path: "/api.v1.Entries/UpdateEntry",
      type: GRPCCallType.unary
    )

    internal static let deleteEntry = GRPCMethodDescriptor(
      name: "DeleteEntry",
      path: "/api.v1.Entries/DeleteEntry",
      type: GRPCCallType.unary
    )

    internal static let listGroupChildren = GRPCMethodDescriptor(
      name: "ListGroupChildren",
      path: "/api.v1.Entries/ListGroupChildren",
      type: GRPCCallType.unary
    )

    internal static let changeParent = GRPCMethodDescriptor(
      name: "ChangeParent",
      path: "/api.v1.Entries/ChangeParent",
      type: GRPCCallType.unary
    )

    internal static let writeFile = GRPCMethodDescriptor(
      name: "WriteFile",
      path: "/api.v1.Entries/WriteFile",
      type: GRPCCallType.clientStreaming
    )

    internal static let readFile = GRPCMethodDescriptor(
      name: "ReadFile",
      path: "/api.v1.Entries/ReadFile",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// Usage: instantiate `Api_V1_PropertiesClient`, then call methods of this protocol to make API calls.
internal protocol Api_V1_PropertiesClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? { get }

  func addProperty(
    _ request: Api_V1_AddPropertyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_AddPropertyRequest, Api_V1_AddPropertyResponse>

  func updateProperty(
    _ request: Api_V1_UpdatePropertyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_UpdatePropertyRequest, Api_V1_UpdatePropertyResponse>

  func deleteProperty(
    _ request: Api_V1_DeletePropertyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_DeletePropertyRequest, Api_V1_DeletePropertyResponse>
}

extension Api_V1_PropertiesClientProtocol {
  internal var serviceName: String {
    return "api.v1.Properties"
  }

  /// Unary call to AddProperty
  ///
  /// - Parameters:
  ///   - request: Request to send to AddProperty.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func addProperty(
    _ request: Api_V1_AddPropertyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_AddPropertyRequest, Api_V1_AddPropertyResponse> {
    return self.makeUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.addProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddPropertyInterceptors() ?? []
    )
  }

  /// Unary call to UpdateProperty
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateProperty.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateProperty(
    _ request: Api_V1_UpdatePropertyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_UpdatePropertyRequest, Api_V1_UpdatePropertyResponse> {
    return self.makeUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.updateProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePropertyInterceptors() ?? []
    )
  }

  /// Unary call to DeleteProperty
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteProperty.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func deleteProperty(
    _ request: Api_V1_DeletePropertyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_DeletePropertyRequest, Api_V1_DeletePropertyResponse> {
    return self.makeUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.deleteProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeletePropertyInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Api_V1_PropertiesClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Api_V1_PropertiesNIOClient")
internal final class Api_V1_PropertiesClient: Api_V1_PropertiesClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.v1.Properties service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Api_V1_PropertiesNIOClient: Api_V1_PropertiesClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol?

  /// Creates a client for the api.v1.Properties service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_V1_PropertiesAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? { get }

  func makeAddPropertyCall(
    _ request: Api_V1_AddPropertyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_AddPropertyRequest, Api_V1_AddPropertyResponse>

  func makeUpdatePropertyCall(
    _ request: Api_V1_UpdatePropertyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_UpdatePropertyRequest, Api_V1_UpdatePropertyResponse>

  func makeDeletePropertyCall(
    _ request: Api_V1_DeletePropertyRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_DeletePropertyRequest, Api_V1_DeletePropertyResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_PropertiesAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_V1_PropertiesClientMetadata.serviceDescriptor
  }

  internal var interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeAddPropertyCall(
    _ request: Api_V1_AddPropertyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_AddPropertyRequest, Api_V1_AddPropertyResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.addProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddPropertyInterceptors() ?? []
    )
  }

  internal func makeUpdatePropertyCall(
    _ request: Api_V1_UpdatePropertyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_UpdatePropertyRequest, Api_V1_UpdatePropertyResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.updateProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePropertyInterceptors() ?? []
    )
  }

  internal func makeDeletePropertyCall(
    _ request: Api_V1_DeletePropertyRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_DeletePropertyRequest, Api_V1_DeletePropertyResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.deleteProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeletePropertyInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_PropertiesAsyncClientProtocol {
  internal func addProperty(
    _ request: Api_V1_AddPropertyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_AddPropertyResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.addProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAddPropertyInterceptors() ?? []
    )
  }

  internal func updateProperty(
    _ request: Api_V1_UpdatePropertyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_UpdatePropertyResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.updateProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePropertyInterceptors() ?? []
    )
  }

  internal func deleteProperty(
    _ request: Api_V1_DeletePropertyRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_DeletePropertyResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_PropertiesClientMetadata.Methods.deleteProperty.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeletePropertyInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Api_V1_PropertiesAsyncClient: Api_V1_PropertiesAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_PropertiesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Api_V1_PropertiesClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'addProperty'.
  func makeAddPropertyInterceptors() -> [ClientInterceptor<Api_V1_AddPropertyRequest, Api_V1_AddPropertyResponse>]

  /// - Returns: Interceptors to use when invoking 'updateProperty'.
  func makeUpdatePropertyInterceptors() -> [ClientInterceptor<Api_V1_UpdatePropertyRequest, Api_V1_UpdatePropertyResponse>]

  /// - Returns: Interceptors to use when invoking 'deleteProperty'.
  func makeDeletePropertyInterceptors() -> [ClientInterceptor<Api_V1_DeletePropertyRequest, Api_V1_DeletePropertyResponse>]
}

internal enum Api_V1_PropertiesClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Properties",
    fullName: "api.v1.Properties",
    methods: [
      Api_V1_PropertiesClientMetadata.Methods.addProperty,
      Api_V1_PropertiesClientMetadata.Methods.updateProperty,
      Api_V1_PropertiesClientMetadata.Methods.deleteProperty,
    ]
  )

  internal enum Methods {
    internal static let addProperty = GRPCMethodDescriptor(
      name: "AddProperty",
      path: "/api.v1.Properties/AddProperty",
      type: GRPCCallType.unary
    )

    internal static let updateProperty = GRPCMethodDescriptor(
      name: "UpdateProperty",
      path: "/api.v1.Properties/UpdateProperty",
      type: GRPCCallType.unary
    )

    internal static let deleteProperty = GRPCMethodDescriptor(
      name: "DeleteProperty",
      path: "/api.v1.Properties/DeleteProperty",
      type: GRPCCallType.unary
    )
  }
}

/// Usage: instantiate `Api_V1_DocumentClient`, then call methods of this protocol to make API calls.
internal protocol Api_V1_DocumentClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? { get }

  func listDocuments(
    _ request: Api_V1_ListDocumentsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_ListDocumentsRequest, Api_V1_ListDocumentsResponse>

  func getDocumentDetail(
    _ request: Api_V1_GetDocumentDetailRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_GetDocumentDetailRequest, Api_V1_GetDocumentDetailResponse>
}

extension Api_V1_DocumentClientProtocol {
  internal var serviceName: String {
    return "api.v1.Document"
  }

  /// Unary call to ListDocuments
  ///
  /// - Parameters:
  ///   - request: Request to send to ListDocuments.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listDocuments(
    _ request: Api_V1_ListDocumentsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_ListDocumentsRequest, Api_V1_ListDocumentsResponse> {
    return self.makeUnaryCall(
      path: Api_V1_DocumentClientMetadata.Methods.listDocuments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListDocumentsInterceptors() ?? []
    )
  }

  /// Unary call to GetDocumentDetail
  ///
  /// - Parameters:
  ///   - request: Request to send to GetDocumentDetail.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getDocumentDetail(
    _ request: Api_V1_GetDocumentDetailRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_GetDocumentDetailRequest, Api_V1_GetDocumentDetailResponse> {
    return self.makeUnaryCall(
      path: Api_V1_DocumentClientMetadata.Methods.getDocumentDetail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDocumentDetailInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Api_V1_DocumentClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Api_V1_DocumentNIOClient")
internal final class Api_V1_DocumentClient: Api_V1_DocumentClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.v1.Document service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Api_V1_DocumentNIOClient: Api_V1_DocumentClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol?

  /// Creates a client for the api.v1.Document service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_V1_DocumentAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? { get }

  func makeListDocumentsCall(
    _ request: Api_V1_ListDocumentsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_ListDocumentsRequest, Api_V1_ListDocumentsResponse>

  func makeGetDocumentDetailCall(
    _ request: Api_V1_GetDocumentDetailRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_GetDocumentDetailRequest, Api_V1_GetDocumentDetailResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_DocumentAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_V1_DocumentClientMetadata.serviceDescriptor
  }

  internal var interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeListDocumentsCall(
    _ request: Api_V1_ListDocumentsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_ListDocumentsRequest, Api_V1_ListDocumentsResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_DocumentClientMetadata.Methods.listDocuments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListDocumentsInterceptors() ?? []
    )
  }

  internal func makeGetDocumentDetailCall(
    _ request: Api_V1_GetDocumentDetailRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_GetDocumentDetailRequest, Api_V1_GetDocumentDetailResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_DocumentClientMetadata.Methods.getDocumentDetail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDocumentDetailInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_DocumentAsyncClientProtocol {
  internal func listDocuments(
    _ request: Api_V1_ListDocumentsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_ListDocumentsResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_DocumentClientMetadata.Methods.listDocuments.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListDocumentsInterceptors() ?? []
    )
  }

  internal func getDocumentDetail(
    _ request: Api_V1_GetDocumentDetailRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_GetDocumentDetailResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_DocumentClientMetadata.Methods.getDocumentDetail.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDocumentDetailInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Api_V1_DocumentAsyncClient: Api_V1_DocumentAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_DocumentClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Api_V1_DocumentClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'listDocuments'.
  func makeListDocumentsInterceptors() -> [ClientInterceptor<Api_V1_ListDocumentsRequest, Api_V1_ListDocumentsResponse>]

  /// - Returns: Interceptors to use when invoking 'getDocumentDetail'.
  func makeGetDocumentDetailInterceptors() -> [ClientInterceptor<Api_V1_GetDocumentDetailRequest, Api_V1_GetDocumentDetailResponse>]
}

internal enum Api_V1_DocumentClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Document",
    fullName: "api.v1.Document",
    methods: [
      Api_V1_DocumentClientMetadata.Methods.listDocuments,
      Api_V1_DocumentClientMetadata.Methods.getDocumentDetail,
    ]
  )

  internal enum Methods {
    internal static let listDocuments = GRPCMethodDescriptor(
      name: "ListDocuments",
      path: "/api.v1.Document/ListDocuments",
      type: GRPCCallType.unary
    )

    internal static let getDocumentDetail = GRPCMethodDescriptor(
      name: "GetDocumentDetail",
      path: "/api.v1.Document/GetDocumentDetail",
      type: GRPCCallType.unary
    )
  }
}

/// Usage: instantiate `Api_V1_NotifyClient`, then call methods of this protocol to make API calls.
internal protocol Api_V1_NotifyClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? { get }

  func getLatestSequence(
    _ request: Api_V1_GetLatestSequenceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_GetLatestSequenceRequest, Api_V1_GetLatestSequenceResponse>

  func listUnSyncedEvent(
    _ request: Api_V1_ListUnSyncedEventRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_ListUnSyncedEventRequest, Api_V1_ListUnSyncedEventResponse>

  func commitSyncedEvent(
    _ request: Api_V1_CommitSyncedEventRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_V1_CommitSyncedEventRequest, Api_V1_CommitSyncedEventResponse>
}

extension Api_V1_NotifyClientProtocol {
  internal var serviceName: String {
    return "api.v1.Notify"
  }

  /// Unary call to GetLatestSequence
  ///
  /// - Parameters:
  ///   - request: Request to send to GetLatestSequence.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getLatestSequence(
    _ request: Api_V1_GetLatestSequenceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_GetLatestSequenceRequest, Api_V1_GetLatestSequenceResponse> {
    return self.makeUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.getLatestSequence.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetLatestSequenceInterceptors() ?? []
    )
  }

  /// Unary call to ListUnSyncedEvent
  ///
  /// - Parameters:
  ///   - request: Request to send to ListUnSyncedEvent.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listUnSyncedEvent(
    _ request: Api_V1_ListUnSyncedEventRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_ListUnSyncedEventRequest, Api_V1_ListUnSyncedEventResponse> {
    return self.makeUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.listUnSyncedEvent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListUnSyncedEventInterceptors() ?? []
    )
  }

  /// Unary call to CommitSyncedEvent
  ///
  /// - Parameters:
  ///   - request: Request to send to CommitSyncedEvent.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func commitSyncedEvent(
    _ request: Api_V1_CommitSyncedEventRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_V1_CommitSyncedEventRequest, Api_V1_CommitSyncedEventResponse> {
    return self.makeUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.commitSyncedEvent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommitSyncedEventInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Api_V1_NotifyClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Api_V1_NotifyNIOClient")
internal final class Api_V1_NotifyClient: Api_V1_NotifyClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.v1.Notify service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Api_V1_NotifyNIOClient: Api_V1_NotifyClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol?

  /// Creates a client for the api.v1.Notify service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_V1_NotifyAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? { get }

  func makeGetLatestSequenceCall(
    _ request: Api_V1_GetLatestSequenceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_GetLatestSequenceRequest, Api_V1_GetLatestSequenceResponse>

  func makeListUnSyncedEventCall(
    _ request: Api_V1_ListUnSyncedEventRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_ListUnSyncedEventRequest, Api_V1_ListUnSyncedEventResponse>

  func makeCommitSyncedEventCall(
    _ request: Api_V1_CommitSyncedEventRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_V1_CommitSyncedEventRequest, Api_V1_CommitSyncedEventResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_NotifyAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_V1_NotifyClientMetadata.serviceDescriptor
  }

  internal var interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetLatestSequenceCall(
    _ request: Api_V1_GetLatestSequenceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_GetLatestSequenceRequest, Api_V1_GetLatestSequenceResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.getLatestSequence.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetLatestSequenceInterceptors() ?? []
    )
  }

  internal func makeListUnSyncedEventCall(
    _ request: Api_V1_ListUnSyncedEventRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_ListUnSyncedEventRequest, Api_V1_ListUnSyncedEventResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.listUnSyncedEvent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListUnSyncedEventInterceptors() ?? []
    )
  }

  internal func makeCommitSyncedEventCall(
    _ request: Api_V1_CommitSyncedEventRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_V1_CommitSyncedEventRequest, Api_V1_CommitSyncedEventResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.commitSyncedEvent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommitSyncedEventInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_V1_NotifyAsyncClientProtocol {
  internal func getLatestSequence(
    _ request: Api_V1_GetLatestSequenceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_GetLatestSequenceResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.getLatestSequence.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetLatestSequenceInterceptors() ?? []
    )
  }

  internal func listUnSyncedEvent(
    _ request: Api_V1_ListUnSyncedEventRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_ListUnSyncedEventResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.listUnSyncedEvent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListUnSyncedEventInterceptors() ?? []
    )
  }

  internal func commitSyncedEvent(
    _ request: Api_V1_CommitSyncedEventRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_V1_CommitSyncedEventResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_V1_NotifyClientMetadata.Methods.commitSyncedEvent.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCommitSyncedEventInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Api_V1_NotifyAsyncClient: Api_V1_NotifyAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_V1_NotifyClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Api_V1_NotifyClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getLatestSequence'.
  func makeGetLatestSequenceInterceptors() -> [ClientInterceptor<Api_V1_GetLatestSequenceRequest, Api_V1_GetLatestSequenceResponse>]

  /// - Returns: Interceptors to use when invoking 'listUnSyncedEvent'.
  func makeListUnSyncedEventInterceptors() -> [ClientInterceptor<Api_V1_ListUnSyncedEventRequest, Api_V1_ListUnSyncedEventResponse>]

  /// - Returns: Interceptors to use when invoking 'commitSyncedEvent'.
  func makeCommitSyncedEventInterceptors() -> [ClientInterceptor<Api_V1_CommitSyncedEventRequest, Api_V1_CommitSyncedEventResponse>]
}

internal enum Api_V1_NotifyClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Notify",
    fullName: "api.v1.Notify",
    methods: [
      Api_V1_NotifyClientMetadata.Methods.getLatestSequence,
      Api_V1_NotifyClientMetadata.Methods.listUnSyncedEvent,
      Api_V1_NotifyClientMetadata.Methods.commitSyncedEvent,
    ]
  )

  internal enum Methods {
    internal static let getLatestSequence = GRPCMethodDescriptor(
      name: "GetLatestSequence",
      path: "/api.v1.Notify/GetLatestSequence",
      type: GRPCCallType.unary
    )

    internal static let listUnSyncedEvent = GRPCMethodDescriptor(
      name: "ListUnSyncedEvent",
      path: "/api.v1.Notify/ListUnSyncedEvent",
      type: GRPCCallType.unary
    )

    internal static let commitSyncedEvent = GRPCMethodDescriptor(
      name: "CommitSyncedEvent",
      path: "/api.v1.Notify/CommitSyncedEvent",
      type: GRPCCallType.unary
    )
  }
}

